name: 'Notify Change'

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  notify:
    name: 'Notify Change'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: nmde/maap-input-parser-testing
          token: ${{ secrets.CI_TOKEN }}
      - name: 'Update submodules'
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: 'Commit updates'
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Update submodules" || echo "No changes to commit"
          git push