name: 'Run Tests'

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    name: 'Run Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Test'
        run: |
          node --experimental-vm-modules .yarn/releases/yarn-3.2.1.cjs jest